-- supabase/schema.sql

-- Eliminar tabla si ya existe (cuidado en producción)
DROP TABLE IF EXISTS public.gifts;

-- Crear tabla
CREATE TABLE public.gifts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  categoria text NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  imagen_url text,
  tienda_url text,
  comprado boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Configurar RLS (Row Level Security)
ALTER TABLE public.gifts ENABLE ROW LEVEL SECURITY;

-- Política 1: Permitir lectura
CREATE POLICY "Permitir lectura publica" ON public.gifts FOR SELECT TO public USING (true);

-- Política 2: Permitir actualización
CREATE POLICY "Permitir actualizacion anonima de estado comprado" ON public.gifts FOR UPDATE TO public USING (true) WITH CHECK (true);

-- Insertar todos los datos
INSERT INTO public.gifts (categoria, nombre, descripcion, imagen_url, tienda_url)
VALUES
  ('Mobiliario y Sueño', 'Coche Moises Travel System Kansas Priori', 'El Coche para Bebe Travel System Moisés Kansas de marca Playful (Priori) brindará seguridad a ti y a tu bebé, diseño moderno, liviano y con cierre compacto, es apto para bebés desde los 0 meses hasta 3 años aproximadamente, cuenta con moisés incluye cubre pies este es apto para usar a favor de la marcha y contra marcha con 3 posiciones de reclinación y soporta un peso hasta 18 Kg, porta bebe con cubre pies, manija diseño tipo cuero de lujo con posiciones y amplia canasta multiusos. Edad recomendada de 0 a 36 - 48 meses aprox Material de la estructura Metal Incluye:Porta bebé con cubrepiés Grupo 0+ Desde los 0 meses hasta los 18 meses aprox Cinturón de seguridad de cinco puntos. Capota XXL con borde metálico reforzado, plegable y visor. Asiento ajustable 3 posiciones de reclinado en ambos sentidos y con ventana de ventilación. Bolsillo adicional en el espaldar. Manija ajustable en 6 posiciones. Tapizado confortable y funda retirable, suave y lavable. Cubrepiés con cremallera. Barra Frontal Extraíble con detalle en cuero de lujo. Freno centralizado en ruedas traseras 2 Ruedas delanteras con giro completo en espuma EVA de 7 pulgadas diseñadas con sistema de absorción de impactos. 2 Ruedas traseras todo terreno en espuma EVA de 10 pulgadas equipadas con sistema de un pie. Canasto amplio en poliéster, para objetos (Portatetero no incluido) Plegado compacto. Material del Tapiz tela: composición 100% poliésterMaterial Capota: 100% poliéster Dimensiones del coche abierto: Ancho: 55 cms, Alto: 108 cms, Largo: 85 cms Dimensiones asiento cuando es coche: Ancho: 34 cms Espaldar: Alto: 40 cms Dimensiones del coche plegado: Ancho: 55 cms, Alto: 46 cms, Largo: 72 cms. Dimensiones de la porta bebe: Ancho: 30 cms, Alto: 32 cms, Largo: 40 cmsPeso de la porta bebe: 2.6 Kg Peso máximo que Soporta la porta bebe: 13 kgPeso del Moisés: 2.9 Kg Peso de la estructura 7 Kg Peso neto del producto 10 kg Peso máximo que Soporta el coche: 15 Kg Medidas del Moisés: Ancho: 33 cms , Profundo: 20 cms, Largo: 77 cms', 'http://mimaitos.com/cdn/shop/files/PHOTO-2024-04-04-12-27-22.jpg?v=1749500122', 'https://www.google.com/search?q=Coche+Moises+Travel+System+Kansas+Priori'),
  ('Mobiliario y Sueño', 'Colecho con música y mecedora', 'El Nuevo Colecho Eléctrico Castillitos combina comodidad, seguridad y tecnología para ofrecer el mejor descanso a tu bebé desde los 0 hasta los 8 meses. Su diseño moderno y funcional incluye una mecedora eléctrica con movimiento suave y música relajante, ideal para acompañar los momentos de sueño y calma. ✨ Característ', 'http://castillitos.com/cdn/shop/files/IMG-7163.png?v=1768858832', 'https://www.google.com/search?q=Colecho+con+música+y+mecedora'),
  ('Mobiliario y Sueño', 'Almohada Anti Reflujo Gris - Nubba', 'Almohada Anti Reflujo - Gris marca Nubba REF 5380. Compra Online en Pepe Ganga para tus hijos y elige Entrega en Tienda', 'https://pepeganga.vtexassets.com/arquivos/ids/1179436/002290-1.png?v=638644321871170000', 'https://www.google.com/search?q=Almohada+Anti+Reflujo+Gris+-+Nubba'),
  ('Mobiliario y Sueño', 'Monitor con cámara 360° LCD 5" (Sin Wifi)', 'Descubre la tranquilidad que ofrece nuestro Monitor con cámara 360° para bebé con pantalla LCD 5". Este dispositivo inalámbrico cuenta con una pantalla digital', 'http://www.coccoylolo.com/cdn/shop/files/MONITOR_360_5-SP960-1.jpg?v=1768776786', 'https://www.google.com/search?q=Monitor+con+cámara+360°+LCD+5"+(Sin+Wifi)'),
  ('Mobiliario y Sueño', 'Sleeping 100% Algodón Orgánico Cloudbaby', 'Descripción. Esta manta unisex se puede utilizar como manta de ropa de bebé, saco de dormir, manta de cochecito o envoltura de cuna. Saco de dormir cómodo para recién nacido con un diseño de gorro resistente al viento se convierte en una manta cálida mientras viajas o juegas afuera con Papá y Mamá. Calidad suave Ligera', 'http://centraldelbebe.com/cdn/shop/products/13_632ab387-10ab-4409-b818-ce2ff0535f16.jpg?v=1658958306', 'https://www.google.com/search?q=Sleeping+100%+Algodón+Orgánico+Cloudbaby'),
  ('Alimentación', 'Silla Comedor Bebé Mila Priori 6 en 1', 'Esta fabulosa Silla comedor será ideal y perfecta para las etapas de crecimiento de tu bebé, ya que cuenta con un novedoso diseño con 6 formas de uso: Silla comedor AltaMesa y silla tipo escritorioSilla individual con bandejaTaburete bajoTaburete altoSilla acolchada Además, cuenta con cinturón de seguridad de 5 puntos,', 'http://mimaitos.com/cdn/shop/files/WhatsApp_Image_2025-01-24_at_07.27.29_3.jpg?v=1762192417', 'https://www.google.com/search?q=Silla+Comedor+Bebé+Mila+Priori+6+en+1'),
  ('Alimentación', 'Set Vajilla Silicona y Acero (6 Piezas)', 'Material seguro y fiable: la vajilla está hecha principalmente en acero inoxidable 18/8 duradero (grado 304 apto para alimentos) y silicona resistente al calor (40% superficie más fría), estos platos irrompibles protegen a los niños de quemaduras, mientras que el diseño a prueba de caídas resiste accidentes diarios, no', 'http://mimaitos.com/cdn/shop/files/11_4fed8fba-7454-408a-afe3-68064e84dc03.png?v=1764883895', 'https://www.google.com/search?q=Set+Vajilla+Silicona+y+Acero+(6+Piezas)'),
  ('Alimentación', 'Set Teteros para Recién Nacidos - Avent Vidrio', 'Set Teteros para Recién Nacidos - Avent marca Avent REF SCD838/11. Compra Online en Pepe Ganga para tus hijos y elige Entrega en tienda', 'https://pepeganga.vtexassets.com/arquivos/ids/1203586/115903305-1.jpg?v=638754790092830000', 'https://www.google.com/search?q=Set+Teteros+para+Recién+Nacidos+-+Avent+Vidrio'),
  ('Alimentación', 'Extractor eléctrico de leche Avent Express', 'Descripción Extractor de Leche Eléctrico Philips Avent SCF323/11Extracción sin esfuerzoEl extractor de leche eléctrico Philips Avent mantiene el flujo de leche en un nivel óptimo y se adapta suavemente a su tamaño y forma. Rápido, cómodo y conveniente para todas las madres de recién nacidos.Experiencia personalizada co', 'http://mimaitos.com/cdn/shop/files/D_NQ_NP_2X_838284-MLU78051091164_082024-F.webp?v=1738677478', 'https://www.google.com/search?q=Extractor+eléctrico+de+leche+Avent+Express'),
  ('Alimentación', 'Baberos Muselina Estampados (Pack x2)', 'Inspiradas en el día a día de los padres, nuestra línea de baberos está diseñada para dar funcionalidad, comodidad y estilo. Son fabricados en tela 100% algodón, no tienen ningún accesorio por lo que funcionan para niños y niñas. Doble botón que permite ajustar al cuello del bebé. Material: 100% Algodón. *Los portachup', 'http://pomboylola.com.co/cdn/shop/files/3N6A5794.jpg?v=1753214225', 'https://www.google.com/search?q=Baberos+Muselina+Estampados+(Pack+x2)'),
  ('Alimentación', 'Baberos Muselina Colores Sólidos', 'Inspiradas en el día a día de los padres, nuestra línea de baberos Essential Colors está diseñada para dar funcionalidad, comodidad y estilo. Son fabricados en tela 100% algodón, no tienen ningún accesorio por lo que funcionan para niños y niñas. Doble botón que permite ajustar al cuello del bebé. Material: 100% Algodó', 'http://pomboylola.com.co/cdn/shop/files/3N6A9907.jpg?v=1753196671', 'https://www.google.com/search?q=Baberos+Muselina+Colores+Sólidos'),
  ('Aseo y Salud', 'Lima de Uñas Eléctrica Bebé', '¿Tienes miedo de cortarle el dedo a tu bebé cuando usas un cortaúñas? ¿Te preocupa que la cara de tu bebé esté rasguñada?¡Con la lima de uñas eléctrica para bebés nunca más tendrás que temer cortar el dedo de un bebé!Con esta lima de uñas para bebés que no daña las cutículas ni los lechos ungueales suaves, puedes recor', 'http://mimaitos.com/cdn/shop/products/D_981286-MCO49648354873_042022-B.jpg?v=1681241277', 'https://www.google.com/search?q=Lima+de+Uñas+Eléctrica+Bebé'),
  ('Aseo y Salud', 'Set de Aseo Madera x4', 'SET DE ASEO MADERA x4 25001', '/assets/971-9712230_my-neighbor-totoro.png', 'https://www.google.com/search?q=Set+de+Aseo+Madera+x4'),
  ('Aseo y Salud', 'Termómetro Infrarrojo Alta Precisión', 'No encontrado', '/assets/971-9712230_my-neighbor-totoro.png', 'https://www.google.com/search?q=Termómetro+Infrarrojo+Alta+Precisión'),
  ('Aseo y Salud', 'Toalla Capucha Hadas', 'Nuestras toallas son elaboradas en fibras naturales ideales para la piel de tu bebé, además cuentan con grandes beneficios de durabilidad y absorbencia. ¡Suaves y absorbentes! Ref: Toalla Capucha Estampada Hadas Medidas: 80 cm x 90 cm (ancho x largo) Material: 100% algodón Cuidados: Lavar la toalla en la lavadora en ci', 'http://pomboylola.com.co/cdn/shop/files/3N6A5705.jpg?v=1739844826', 'https://www.google.com/search?q=Toalla+Capucha+Hadas'),
  ('Aseo y Salud', 'Toalla para bebé algodón crudo', 'Toalla con capucha elaborada en 100% Algodón NO sostenible brinda suavidad al bebe Medidas: 76 x 7 6 cm Peso 320 gms', 'http://www.babyfresh.co/cdn/shop/files/toki-toalla-crudo-8584-717275_008584-1.jpg?v=1766185987', 'https://www.google.com/search?q=Toalla+para+bebé+algodón+crudo'),
  ('Pañaleras y Paseo', 'Pañalera solapa diseño estampado', 'La Pañalera solapa con diseño estampado esta elaborada en tela de alta calidad, resistente al agua, fácil de limpiar. De gran capacidad y con bolsillos térmicos', 'http://www.coccoylolo.com/cdn/shop/files/PANALERA-ESTAMPADA_SOLAPA-2.jpg?v=1768777147', 'https://www.google.com/search?q=Pañalera+solapa+diseño+estampado'),
  ('Pañaleras y Paseo', 'Pañalera Multifuncional con Cambiador', 'Encuentra Pañalera Multifuncional con Cambiador Verde GENERICO a precios espectaculares, elige el modelo perfecto para ti y aprovecha nuestras ofertas online.', 'https://media.falabella.com/FalabellaPEAndCO/NoImage/public', 'https://www.google.com/search?q=Pañalera+Multifuncional+con+Cambiador'),
  ('Pañaleras y Paseo', 'Cambiador Portable - Hadas', 'Cambia a tu bebé de una manera cómoda y práctica!!! Nuestros cambiadores son acolchados, fáciles de guardar en la pañalera por su sistema de plegado tipo bolsita y su protector impermeable. Ref: Cambiador Hadas Medidas: 45cm x 66cm (ancho x largo) Material: Exterior Tela Antifluido/Interior Impermeable Cuidados: Lavar ', 'http://pomboylola.com.co/cdn/shop/files/Recurso22.png?v=1744509730', 'https://www.google.com/search?q=Cambiador+Portable+-+Hadas'),
  ('Pañaleras y Paseo', 'Pack Muselinas Bebé Multicolor (Zara Home)', 'No encontrado', '/assets/971-9712230_my-neighbor-totoro.png', 'https://www.google.com/search?q=Pack+Muselinas+Bebé+Multicolor+(Zara+Home)'),
  ('Pañaleras y Paseo', 'Manta Muselina - Safari', 'Nuestras mantas están hechas con 2 capas de muselina de algodón, son muy suaves, transpirables. Son perfectas para envolver a tu pequeño, usar en el coche o en el sofá y para abrigarlo en su cuna. Incluye borlas en las esquinas de la manta. Ref: Manta Muselina Hadas Medidas: 1mt x 1mt (ancho x largo) Material: 100% alg', 'http://pomboylola.com.co/cdn/shop/files/3N6A0263-scaled.jpg?v=1738873689', 'https://www.google.com/search?q=Manta+Muselina+-+Safari'),
  ('Estimulación y Libros', 'Tapete de agua inflable Tummy Time', '¡Convierte el "Tummy Time" en una aventura submarina inolvidable! ¿A tu bebé le cuesta estar boca abajo? El Tapete de Agua Inflable para Bebé de Mimaitos es la herramienta sensorial perfecta para que tu pequeño fortalezca sus músculos mientras se divierte explorando un mundo de colores y movimiento. Beneficios clave pa', 'http://mimaitos.com/cdn/shop/files/Tapete_de_agua_inflable_para_beb.jpg?v=1774037675', 'https://www.google.com/search?q=Tapete+de+agua+inflable+Tummy+Time'),
  ('Estimulación y Libros', 'Libro de tela: Alegres Animales', 'Los libros de tela interactivos son una excelente opción para estimular el desarrollo sensorial y cognitivo de los bebés y niños pequeños. Colorea con agua, deja secar y ¡vuelve colorear! Incluye 1 pincel tipo marcador', 'https://panamericana.vtexassets.com/arquivos/ids/631475/Libro-de-tela--alegres-animales.jpg?v=639016646617630000', 'https://www.google.com/search?q=Libro+de+tela:+Alegres+Animales'),
  ('Estimulación y Libros', 'Libro de tela con textura', 'Libro de tela suave con diferentes texturas que estimulan el tacto y la curiosidad de tu bebé. Ideal desde los primeros meses de vida. Lavable.', 'http://enfantasy.com.co/cdn/shop/files/bebeLOGO_78d9a7de-86f6-4f52-86e1-47d9d70f7623.jpg?v=1760750663', 'https://www.google.com/search?q=Libro+de+tela+con+textura'),
  ('Estimulación y Libros', 'Tapete Alfombra Plegable Antigolpes', 'Encuentra Tapete Alfombra Plegable Reversible Antigolpes Para Niños ROUX a precios espectaculares, elige el modelo perfecto para ti y aprovecha nuestras ofertas online.', 'https://media.falabella.com/falabellaCO/152314143_01/public', 'https://www.google.com/search?q=Tapete+Alfombra+Plegable+Antigolpes'),
  ('Estimulación y Libros', 'Cartas Didácticas Estimulación Visual (45 pcs)', 'Encuentra Cartas Didácticas Estimulación Visual para Bebés x 45 Piezas RONDA a precios espectaculares, elige el modelo perfecto para ti y aprovecha nuestras ofertas online.', 'https://media.falabella.com/falabellaCO/148197884_01/public', 'https://www.google.com/search?q=Cartas+Didácticas+Estimulación+Visual+(45+pcs)'),
  ('Estimulación y Libros', 'Gimnasio Artesanal Mr Fox', 'Esta fabricado en madera de pino y pintado con barniz a base de agua, un juguete Ecofrendly que además de ser respetuoso con el medio ambiente, le ayudará a favorecer el desarrollo cerebral de su bebé. Incluye 5 juguetes colgantes de diferentes tamaños y texturas donde podrán estimular sus sentidos. ( Zebra, Elefante, ', 'http://www.babystation.com.co/cdn/shop/files/selva.webp?v=1766974316', 'https://www.google.com/search?q=Gimnasio+Artesanal+Mr+Fox'),
  ('Estimulación y Libros', 'Libro Mujercitas Ilustrado', 'Clásicos de la literatura de aventuras, que han cautivado a millones de lectores en todo el mundo. Historias divertidas y emocionantes, magníficamente ilustradas.', 'https://www.lexuseditores.com.co/wp-content/uploads/2022/02/MNJMU1.jpg', 'https://www.google.com/search?q=Libro+Mujercitas+Ilustrado'),
  ('Ropa y Conjuntos', 'Kit Primer Amor', 'Cuidado y protección para los primeros momentos. El Kit Primer Amor contiene todo lo necesario para mantener a tu bebé limpio y seguro: 1 Escurridor portátil: Práctico y fácil de usar para secar biberones y más. 1 Detergente hipoalergénico de 1L: Suave y seguro para la piel sensible de tu bebé. 1 Limpiador de biberones', 'http://gugasens.com/cdn/shop/files/DSC_2109.jpg?v=1733857702', 'https://www.google.com/search?q=Kit+Primer+Amor'),
  ('Ropa y Conjuntos', 'Overol jardinera algodón índigo', 'Dale la comodidad y seguridad adecuada a tu bebé en cada etapa de su crecimiento con nuestras prendas. De venta en la tienda online Baby Fresh.', 'http://www.babyfresh.co/cdn/shop/files/BF_Logo2.jpg?v=1754668363', 'https://www.google.com/search?q=Overol+jardinera+algodón+índigo'),
  ('Ropa y Conjuntos', 'Conjunto vestido + bloomer bebé niña', 'Vestido corto con panty Elaborado en algodón tela ligera con textura tipo gasa el cual Proporciona suavidad confort frescura y transpirable Ideal para climas cálidos y pieles sensibles Vestido man ga corta con Perilla en frente con botones para mayor facilidad al vestir y desvestir al bebé Panty con elástico en cintura', 'http://www.babyfresh.co/cdn/shop/files/kufim-amarillo-15447-748141_015447-1_19b48d91-3fdf-4f28-bf98-7b281ae80842.jpg?v=1767827327', 'https://www.google.com/search?q=Conjunto+vestido+++bloomer+bebé+niña'),
  ('Ropa y Conjuntos', 'Jogger algodón x2 (Unisex)', 'Set de pantalón largo Elaborado en algodón sostenible Proporciona suavidad y frescura ideal para la piel del bebé Cintura elástica para adaptarse mejor al cuerpo Haladera corta y semi funcional que br inda seguridad Elástico en las botas Con marquilla estampada para mayor comodidad', 'http://www.babyfresh.co/cdn/shop/files/brody-x2-unisex-surtido-4000-748311_004000-1_77c465f9-eb6e-4053-a40a-b1b1c995923a.jpg?v=1757607273', 'https://www.google.com/search?q=Jogger+algodón+x2+(Unisex)'),
  ('Ropa y Conjuntos', 'Jogger algodón x2 (Niña)', 'Consigue los 2 joggers surtidos para niña en Baby Fresh. Confortables, versátiles y perfectos para cualquier ocasión. Ideal para mantener a tu pequeña cómoda y a la moda. ¡Compra ahora y asegura su estilo único! Envío rápido y seguro. ¡Haz tu pedido hoy mismo!', 'http://www.babyfresh.co/cdn/shop/files/jannik-x2-surtido-7000-746842_007000-1_b5a647bf-2a87-4d5a-8156-96645e0e8b2d.jpg?v=1731098293', 'https://www.google.com/search?q=Jogger+algodón+x2+(Niña)'),
  ('Ropa y Conjuntos', 'Body manga sisa x2 (Unisex)', 'Descubre el Set de 2 Bodys Cuello Redondo Manga Sisa Blancos de BabyFresh, hechos de algodón sostenible. Suave, transpirable e hipoalergénica, ofrecen frescura ideal para la piel de tu bebé. Con botones de presión para facilitar el vestir, son imprescindibles. ¡Compra ahora y asegura el confort y estilo de tu pequeño!', 'http://www.babyfresh.co/cdn/shop/files/solecito-x2-blanco-900-725033_000900-2_ad3db66e-8fec-4651-a436-96daa5da20c3.jpg?v=1733860702', 'https://www.google.com/search?q=Body+manga+sisa+x2+(Unisex)'),
  ('Ropa y Conjuntos', 'Body manga larga x2 (Unisex)', 'Viste a tu pequeño con nuestros 2 bodys cuello redondo manga larga, hechos de algodón sostenible y hipoalergénico. Suaves y transpirables, son ideales para la piel del bebé. Con hombros adelantados y botones de presión, facilitan el vestir. ¡Compra ahora y brinda comodidad y frescura a tu bebé!', 'http://www.babyfresh.co/cdn/shop/files/bombom-x2-blanco-900-725032_000900-5.jpg?v=1733860504', 'https://www.google.com/search?q=Body+manga+larga+x2+(Unisex)'),
  ('Ropa y Conjuntos', 'Body botones a presión x5 (Niña)', 'Set de Bodies cuello redondo manga corta Elaborado en algodón el cual proporciona suavidad y frescu ra ideal para la piel del bebé Hombro adelantado para facilidad al vestir y desvestir al bebé Botone s de presión en entrepierna para mayor facilidad al vestir Con marquilla estampada para brindar como didad evitando mol', 'http://www.babyfresh.co/cdn/shop/files/cometa-nina-x5-surtido-9810-711441_009810-1_8deb6fae-a70e-49ea-8d44-3fd63e1f8937.jpg?v=1772746562', 'https://www.google.com/search?q=Body+botones+a+presión+x5+(Niña)'),
  ('Ropa y Conjuntos', 'Body manga larga x2 (Niña)', 'Dale la comodidad y seguridad adecuada a tu bebé en cada etapa de su crecimiento con nuestras prendas. De venta en la tienda online Baby Fresh.', 'http://www.babyfresh.co/cdn/shop/files/keyut-nina-x2-surtido-9806-748490_009806-1_fc3db08d-1e8a-419a-92fb-3dbed9176906.jpg?v=1759502307', 'https://www.google.com/search?q=Body+manga+larga+x2+(Niña)'),
  ('Ropa y Conjuntos', 'Enterizo Punto Eden', 'Enterizo manga larga con puños acanalados y cómodos a prueba de viento. De tejido de punto en algodón suave y agradable a la piel, cuello grueso para mantener a tu mirkat calientico y evitar la entrada de aire frío. Elegante, sobrio perfecto para salir con tu mirkat. Material : 100% Algodón Color : Lila *Los bebés crec', 'http://babymirkat.com/cdn/shop/files/2-Edited_0167e462-6623-48a9-959d-531fb69530fc.jpg?v=1767546109', 'https://www.google.com/search?q=Enterizo+Punto+Eden'),
  ('Ropa y Conjuntos', 'Enterizo Emma', 'Enterizo de algodón grueso y térmico pero flexible con el objetivo de mantener a tu mirkat cómodo como si estuviera piel con piel con mamá, es perfecto para ser la segunda o tercera capa sin necesidad de cobija, el swaddle o el sleeping bag que estés utilizando. Elaborado en algodón muy suave y delicado con su piel. Vi', 'http://babymirkat.com/cdn/shop/files/enterizo-emma-1.png?v=1773832665', 'https://www.google.com/search?q=Enterizo+Emma'),
  ('Ropa y Conjuntos', 'Pijama Enteriza + Gorro Aves (Carter''s)', 'Set Pijama Enteriza y Gorro Estampado Aves Bebés Unisex - Carter''s marca Carters REF 1S944510. Compra Online en Pepe Ganga para tus hijos y elige Entrega en tienda', 'https://pepeganga.vtexassets.com/arquivos/ids/1263869/1S944510-125936790-1.jpg?v=638918984651730000', 'https://www.google.com/search?q=Pijama+Enteriza+++Gorro+Aves+(Carter''s)'),
  ('Ropa y Conjuntos', 'Pijama en Algodón Diseño Spring', 'Pijama confeccionada en suave algodón, perfecto para la hora de dormir o jugar en el dia. Características: Cremallera desde el tobillo hasta la barbilla Puños acanalados Pijama con piecitos Cuidado de las telas: 100% algodón Importado Lavable en la lavadora', 'http://elroperitonline.com.co/cdn/shop/files/1U617410.jpg?v=1771085212', 'https://www.google.com/search?q=Pijama+en+Algodón+Diseño+Spring'),
  ('Ropa y Conjuntos', 'Pijama botones a presión x2 (Niña)', 'Pijama bebé niña con botones a presión manga larga – Set x2👶✨ Este set incluye dos mamelucos de manga larga elaborados en 100% algodón (fibra natural, suave y antialérgica que brinda confort y frescura). La tela jersey ligera permite que el bebé se mantenga cómodo y con libertad de movimiento. Su sistema de broches a p', 'http://www.babyfresh.co/cdn/shop/files/ensueno-nina-x2-surtido-9810-745848_009810-1.jpg?v=1768579222', 'https://www.google.com/search?q=Pijama+botones+a+presión+x2+(Niña)'),
  ('Ropa y Conjuntos', 'Pijama botones a presión x2 (Unisex)', 'Pijama bebé unisex con botones a presión manga larga – Set x2👶✨ Este set incluye dos mamelucos de manga larga elaborados en 100% algodón (fibra natural, suave y antialérgica que brinda confort y frescura). La tela jersey ligera permite que el bebé se mantenga cómodo y con libertad de movimiento. Su sistema de broches a', 'http://www.babyfresh.co/cdn/shop/files/ensueno-unisex-x2-surtido-26298-745960_026298-1_38180cde-5f13-4e61-91a1-59b6bba1d60d.jpg?v=1772746816', 'https://www.google.com/search?q=Pijama+botones+a+presión+x2+(Unisex)'),
  ('Ropa y Conjuntos', 'Jean recto índigo medio (Unisex)', 'Pantalón largo Elaborado en algodón Cintura ajustable para adaptarse mejor al cuerpo y mayor comodid ad Botón de presión en la cintura para mayor facilidad al vestir', 'http://www.babyfresh.co/cdn/shop/files/kozoz-indigo-medio-40200-749101_040200-1.jpg?v=1760991608', 'https://www.google.com/search?q=Jean+recto+índigo+medio+(Unisex)'),
  ('Ropa y Conjuntos', 'Conjunto camiseta + enterizo algodón', 'Camiseta:Está confeccionada en 100% algodón, fibra natural antialérgica y transpirable que brinda suavidad, confort y frescura 🌿. Su tela jersey ligera, natural, transpirable y elástica brinda suavidad y confort, ajustándose al cuerpo con acabados limpios. Es de manga corta con puños sesgados, cuello redondo y perilla ', 'http://www.babyfresh.co/cdn/shop/files/kapid-verde-estampado-39680-748489_039680-1_00d6685c-e4b5-4a7e-9f02-41f9d7e94904.jpg?v=1757510769', 'https://www.google.com/search?q=Conjunto+camiseta+++enterizo+algodón'),
  ('Ropa y Conjuntos', 'Jardinera para bebé niña con recogido', 'Jardinera OFFCORSS para bebé niña. Cómoda y con tierno detalle recogido en la cintura.', 'https://offcorss.vtexassets.com/arquivos/ids/919662/Overall-jardinera-para-bebe-nina.jpg?v=638828346174170000', 'https://www.google.com/search?q=Jardinera+para+bebé+niña+con+recogido'),
  ('Ropa y Conjuntos', 'Vestido Charlotte', 'Hay prendas que cuentan historias y nuestro vestido Charlotte es una de ellas. Confeccionado en 100% Lino, destaca por su icónico cuello Peter Pan en contraste y un delicado lazo frontal que evoca la dulzura de la infancia clásica. Los botones de madera natural añaden ese toque rústico y artesanal que tanto nos gusta. ', 'http://www.monneco.com/cdn/shop/files/3_4_2fa59304-2f60-4e83-9ad1-b096ef06e4a6.jpg?v=1772735040', 'https://www.google.com/search?q=Vestido+Charlotte'),
  ('Ropa y Conjuntos', 'Bonete Bolerito (1-9 meses)', 'Monné & Co ®', 'http://www.monneco.com/cdn/shop/files/2_5_5a967d0e-9b46-4150-88de-b70fcc4518e9.jpg?v=1772149550', 'https://www.google.com/search?q=Bonete+Bolerito+(1-9+meses)'),
  ('Ropa y Conjuntos', 'Medias largas pack x6 (Niña)', 'Medias largas para bebé niña – Paquete x6Elaboradas en algodón sostenible 🌿 que protege y cuida la piel delicada de tu bebita 🧸. Su tejido es suave, fresco y antialérgico ✨, con fibra térmica (se adapta al clima: aporta frescura en días cálidos y calor en los fríos) para mayor bienestar 🤗. Incorporan tejido de media to', 'http://www.babyfresh.co/cdn/shop/files/brenda-x6-surtido-9814-800723_009814-1.jpg?v=1770149934', 'https://www.google.com/search?q=Medias+largas+pack+x6+(Niña)'),
  ('Ropa y Conjuntos', 'Media pantalón blancas x3 (Niña)', 'Descubre nuestras medias pantalón blancas, elaboradas con algodón y fibra térmica que se adapta a cualquier clima. Proporcionan frescura en verano y calor en invierno, además de una suave absorción de humedad. Con talón para mayor comodidad al calzar. ¡Viste a tu hijo con estilo y confort, compra ahora!', 'http://www.babyfresh.co/cdn/shop/files/bunuar-blanco-963-114334_000963-1.jpg?v=1746554701', 'https://www.google.com/search?q=Media+pantalón+blancas+x3+(Niña)');